# **Inverse of a Matrix**

#### Definition

The **inverse of a square matrix** $A$ is another matrix $A^{-1}$ such that:

$$
A A^{-1} = A^{-1} A = I
$$

Where:

- $A$ is a square matrix
- $A^{-1}$ is its inverse
- $I$ is the identity matrix of the same size

#### Conditions for Invertibility

A matrix **has an inverse** if and only if:
1. It is **square** (same number of rows and columns).
2. Its **determinant is non-zero**:  
   $$
   \det(A) \neq 0
   $$

Such matrices are called **non-singular**. If a matrix cannot be inverted, it's called **singular**.

#### Properties

- $A^{-1} A = I$
- $(A^{-1})^{-1} = A$
- $(AB)^{-1} = B^{-1} A^{-1}$
- $(A^T)^{-1} = (A^{-1})^T$

#### Use Cases

- Solving systems of equations: $A \vec{x} = \vec{b}$ ⟶ $\vec{x} = A^{-1} \vec{b}$
- Matrix division (conceptually, since matrix division isn't defined)


### **Code Implementation**

In [5]:
import numpy as np
from numpy.linalg import inv, det
from IPython.display import display, Markdown

# Invertible 3x3 matrix
A = np.array([
    [2, 1, 1],
    [1, 3, 2],
    [1, 0, 0]
])

# Check if matrix is invertible first
d = det(A)
if np.isclose(d, 0):
    raise ValueError("Matrix is not invertible (determinant is zero)")

# Compute inverse
A_inv = inv(A)

# Identity check (with rounding to handle floating-point precision)
I1 = np.round(A @ A_inv, 10)  # Round to 10 decimal places
I2 = np.round(A_inv @ A, 10)

# Display results with more information
display(Markdown("**Matrix $A$**"))
display(A)

display(Markdown(f"**Determinant of $A$: {d:.2f}**"))

display(Markdown("**Inverse $A^{-1}$ (computed numerically)**"))
display(A_inv)

display(Markdown("**$A \\cdot A^{-1}$ (should be identity matrix)**"))
display(I1)

display(Markdown("**$A^{-1} \\cdot A$ (should be identity matrix)**"))
display(I2)

# Verify if both products are identity matrices
is_identity1 = np.allclose(I1, np.eye(3))
is_identity2 = np.allclose(I2, np.eye(3))

display(Markdown(f"**Verification:** $AA^{{-1}}$ is identity: {is_identity1}, $A^{{-1}}A$ is identity: {is_identity2}"))

**Matrix $A$**

array([[2, 1, 1],
       [1, 3, 2],
       [1, 0, 0]])

**Determinant of $A$: -1.00**

**Inverse $A^{-1}$ (computed numerically)**

array([[ 0.,  0.,  1.],
       [-2.,  1.,  3.],
       [ 3., -1., -5.]])

**$A \cdot A^{-1}$ (should be identity matrix)**

array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [ 0.,  0.,  1.]])

**$A^{-1} \cdot A$ (should be identity matrix)**

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0., -0.,  1.]])

**Verification:** $AA^{-1}$ is identity: True, $A^{-1}A$ is identity: True