# Permutation Matrix – Manual Construction of $P$

This section demonstrates how to manually construct a **permutation matrix** $P$ to reorder the rows of a matrix $A$.

The permutation matrix $P$ is defined such that:

$$
PA = A'
$$

Where:
- $A$ is the original matrix  
- $A'$ is the row-reordered version of $A$  
- $P$ is a **permutation matrix**, formed by swapping rows of the identity matrix

## Example: Swapping Rows

Suppose we have:

$$
A =
\begin{bmatrix}
2 & 4 & 1 \\
0 & 0 & 3 \\
0 & 6 & 5
\end{bmatrix}
$$

We want to **swap row 2 and row 3** (i.e., move the third row to second place).  
To do this, we construct the permutation matrix by **swapping rows 2 and 3 of the identity matrix**:

$$
P =
\begin{bmatrix}
1 & 0 & 0 \\
0 & 0 & 1 \\
0 & 1 & 0
\end{bmatrix}
$$

Then,

$$
PA =
\begin{bmatrix}
2 & 4 & 1 \\
0 & 6 & 5 \\
0 & 0 & 3
\end{bmatrix}
$$

## Key Properties of Permutation Matrices

- A permutation matrix is always a **square** matrix.
- Each row and each column has exactly **one entry of 1**, all others are 0.
- Permutation matrices are **orthogonal**: $P^{-1} = P^T$
- Multiplying $P \cdot A$ reorders the **rows** of $A$
- Commonly used in **LU decomposition with partial pivoting** to bring the largest pivot to the top.


---
# Brute Force

In [1]:
import numpy as np

A = np.array([
    [2, 4, 1],
    [0, 0, 3],
    [0, 6, 5]
], dtype=float)

P = np.array([
    [1, 0, 0],
    [0, 0, 1],
    [0, 1, 0]
], dtype=float)

PA = P @ A

print("Permuted Matrix PA:")
print(PA)

Permuted Matrix PA:
[[2. 4. 1.]
 [0. 6. 5.]
 [0. 0. 3.]]


---
# Modified

In [3]:
# Bring the row with the max absolute value in column 0 to the top
pivot_col = 0
max_row = np.argmax(np.abs(A[:, pivot_col]))

# Create permutation matrix
P = np.eye(3)
P[[0, max_row]] = P[[max_row, 0]]

print("Permuted Matrix PA:")
print(PA)

Permuted Matrix PA:
[[2. 4. 1.]
 [0. 6. 5.]
 [0. 0. 3.]]
