# Gaussian Elimination - Constructing Elimination Matrix P

This notebook demonstrates how to manually perform **Gaussian elimination** on a 3×3 matrix `A`, while constructing the **elimination matrix** `P` such that:

$$
PA = U
$$

Where:
- `A` is the original matrix
- `U` is the upper triangular form of `A`
- `P` is the product of **elementary elimination matrices**

### Goal

Transform `A` into an upper triangular matrix `U` by eliminating entries below the main diagonal, and track each row operation using corresponding matrices.

### Elimination Steps

Each row operation is represented by an **elementary matrix**, derived from the identity matrix by changing a single off-diagonal value:

- **`E1`** eliminates `A[1][0]`
- **`E2`** eliminates `A[2][0]`
- **`E3`** eliminates `A[2][1]`

These matrices are multiplied in **reverse order of operations** to build the final elimination matrix:

$$
P = E3 \cdot E2 \cdot E1
$$

Applying this matrix gives the upper triangular form:

$$
U = PA
$$

The same row operations are applied to the vector `b`, so solving the original system `Ax = b` becomes solving `Ux = Pb` via back-substitution.

---
# Brute Force Example

In [61]:
import numpy as np

# Matrices
A = np.array([
    [1, 2, 3],
    [2, 5, 8],
    [3, 7, 10]
], dtype=float)

original_A = A.copy()

b = np.array([1, 2, 1], dtype=float)

I = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]], dtype=float)


# First Elimination Step 
pivot1 = A[0][0]
E21 = A[1][0]  # element to eliminate (row 2, col 1)
A[1] = A[1] - (E21 / pivot1) * A[0]  
b[1] = b[1] - (E21 / pivot1) * b[0]  
# First E
E1 = I.copy()
E1[1][0] = -1 * (E21 / pivot1)



# Second Elimination Step
pivot1 = A[0][0]
E31 = A[2][0]
A[2] = A[2] - (E31 / pivot1) * A[0]  
b[2] = b[2] - (E31 / pivot1) * b[0]
# Second E
E2 = I.copy()
E2[2][0] = -1 * (E31 / pivot1)


# Third Elimination Step 
pivot2 = A[1][1]
E32 = A[2][1]
A[2] = A[2] - (E32 / pivot2) * A[1]  
b[2] = b[2] - (E32 / pivot2) * b[1]
# Third E
E3 = I.copy()
E3[2][1] = -1 * (E32 / pivot2)



# Final elimination matrix P = E3 @ E2 @ E1
P = E3 @ E2 @ E1

print("Upper Triangular Matrix U:")
print(A)
print("\nModified b:")
print(b)
print("\nElimination Matrix P such that PA = U:")
print(P)

# Confirm: P @ Original A should match U
original_A = np.array([
    [1, 2, 3],
    [2, 5, 8],
    [3, 7, 10]
], dtype=float)

print("\nCheck P @ A:")
print(P @ original_A)

Upper Triangular Matrix U:
[[ 1.  2.  3.]
 [ 0.  1.  2.]
 [ 0.  0. -1.]]

Modified b:
[ 1.  0. -2.]

Elimination Matrix P such that PA = U:
[[ 1.  0.  0.]
 [-2.  1.  0.]
 [-1. -1.  1.]]

Check P @ A:
[[ 1.  2.  3.]
 [ 0.  1.  2.]
 [ 0.  0. -1.]]


---
# Modified Example

In [30]:
import numpy as np

# Original matrix and vector
A = np.array([
    [1, 2, 3],
    [2, 5, 8],
    [3, 7, 10]
], dtype=float)

b = np.array([1, 2, 1], dtype=float)

# Identity matrix for elimination matrices
I = np.identity(3)

# Step 1: Eliminate A[1][0]
pivot1 = A[0][0]
m21 = A[1][0] / pivot1
E1 = I.copy()
E1[1][0] = -m21
A = E1 @ A
b = E1 @ b

# Step 2: Eliminate A[2][0]
m31 = A[2][0] / A[0][0]  # Note: Use updated A[2][0]
E2 = I.copy()
E2[2][0] = -m31
A = E2 @ A
b = E2 @ b

# Step 3: Eliminate A[2][1]
pivot2 = A[1][1]
m32 = A[2][1] / pivot2
E3 = I.copy()
E3[2][1] = -m32
A = E3 @ A
b = E3 @ b

# Final elimination matrix P = E3 @ E2 @ E1
P = E3 @ E2 @ E1

print("Upper Triangular Matrix U:")
print(A)
print("\nModified b:")
print(b)
print("\nElimination Matrix P such that PA = U:")
print(P)

# Confirm: P @ Original A should match U
original_A = np.array([
    [1, 2, 3],
    [2, 5, 8],
    [3, 7, 10]
], dtype=float)

print("\nCheck P @ A:")
print(P @ original_A)

Upper Triangular Matrix U:
[[ 1.  2.  3.]
 [ 0.  1.  2.]
 [ 0.  0. -1.]]

Modified b:
[ 1.  0. -2.]

Elimination Matrix P such that PA = U:
[[ 1.  0.  0.]
 [-2.  1.  0.]
 [-1. -1.  1.]]

Check P @ A:
[[ 1.  2.  3.]
 [ 0.  1.  2.]
 [ 0.  0. -1.]]
